[tool.poetry]
name = "gino_admin"
version = "0.0.1dev02"
description = "Admin Panel for DB with Gino ORM and Sanic (inspired by Flask-Admin)"
authors = ["xnuinside <xnuinside@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
sanic-auth = "^0.2.0"
Sanic = "^19.12.2"
gino = "^0.8.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
